services:
  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    image: chat-evaluator
    command: ["python", "-m", "analyze.run"]
    volumes:
      - ./datasets:/app/datasets
      - ./results:/app/results
